# Generated by Django 3.0.2 on 2020-01-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=20)),
                ('logo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='breweries.Brewery')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('full_price', models.CharField(max_length=10)),
                ('flight_price', models.CharField(max_length=10)),
                ('glassware', models.CharField(max_length=20)),
                ('abv', models.TextField(max_length=10)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='breweries.Brewery')),
            ],
        ),
    ]
