# Generated by Django 3.0.2 on 2020-01-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Beer',
        ),
    ]
