# Generated by Django 3.0.2 on 2020-01-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_auto_20200127_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beers', to='breweries.Brewery'),
        ),
        migrations.AlterField(
            model_name='food',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food', to='breweries.Brewery'),
        ),
    ]
