# Generated by Django 3.0.2 on 2020-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0005_auto_20200128_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='ibus',
            field=models.CharField(default=20, max_length=10),
            preserve_default=False,
        ),
    ]
