# Generated by Django 3.0.2 on 2020-01-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0006_beer_ibus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='hours',
            new_name='friday_hours',
        ),
        migrations.AddField(
            model_name='brewery',
            name='monday_hours',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='saturday_hours',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='sunday_hours',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='thursday_hours',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='tuesday_hours',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='wednesday_hours',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
