# Generated by Django 3.0.2 on 2020-01-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0007_auto_20200128_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='options',
            field=models.CharField(default=32, max_length=100),
            preserve_default=False,
        ),
    ]
