# Generated by Django 3.0.2 on 2020-01-28 21:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0010_beer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='beer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=1, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brewery',
            name='logo_url',
            field=models.TextField(max_length=255),
        ),
    ]
