# Generated by Django 3.0.2 on 2020-01-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0011_auto_20200128_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='beer',
        ),
    ]
