# Generated by Django 3.0.2 on 2020-01-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0014_remove_brewery_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='logo_url',
            field=models.TextField(),
        ),
    ]
