# Generated by Django 3.0.2 on 2020-01-28 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0015_auto_20200128_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='beer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=1, size=None),
            preserve_default=False,
        ),
    ]
