# Generated by Django 3.0.2 on 2020-01-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0016_brewery_beer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='beer',
        ),
    ]
