# Generated by Django 3.0.2 on 2020-01-28 22:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0017_remove_brewery_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='drink',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
