# Generated by Django 3.0.2 on 2020-01-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0018_brewery_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='drink',
        ),
    ]
