# Generated by Django 3.0.2 on 2020-01-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0019_remove_brewery_drink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'ordering': ['name']},
        ),
    ]
