# Generated by Django 3.0.2 on 2020-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0020_auto_20200129_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='services_offered',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
