# Generated by Django 3.0.2 on 2020-01-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0021_brewery_services_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='services_offered',
        ),
    ]
