# Generated by Django 3.0.2 on 2020-01-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0022_remove_brewery_services_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.TextField(),
        ),
    ]
