# Generated by Django 3.0.2 on 2020-01-31 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0028_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
